### ISSUE TITLE
it's a wrong 

### ISSUE THREAD

**Issue by 98Kstar** [phra/x0rro#4]
radare2 3.9 0 @ linux-x86-64 git.3.9
commit: unknown build: 2019-10-30__09:02:13

 .--.     .-------------------------------------.
 | _|_    |                                     |
 | O O   <  Processing /root/nbs.exe-obfuscated |
 |  ||    |                                     |
 | _:|    `-------------------------------------'
 |   |
 `---'

 .--.     .-----------------------------------------------------.
 | _|     |                                                     |
 | O O   <  Making segments rwx: all - /root/nbs.exe-obfuscated |
 |  |  |  |                                                     |
 || | /   `-----------------------------------------------------'
 |`-'|
 `---'

making .text rwx
making .rdata rwx
making .data rwx

TypeError: Cannot read property 'trim' of undefined
    at create_stub (/usr/local/lib/node_modules/x0rro/lib/core/x0rro.js:141:83)
    at process._tickCallback (internal/process/next_tick.js:68:7)

my os is kali

**Comment by phra** [comment]
Can you please add the options you selected in the wizard or the command used? Thanks
